name: GameChest
version: 1.0
author: ByteList
website: https://bytelist.de/

main: de.gamechest.GameChest

loadbefore: [ClickAttack, Lobby, ShulkerDefence, DeathRun, JumpDuell, Survival, BuildPlugin, GameChestPoll, GameChestVerify]

commands:
  opme:
  serverid:
    aliases: [sid]
  nick:
  fakeplugins: