name: GameChest
version: mvn:unknown
#description
author: ByteList
main: de.gamechest.GameChest

loadbefore: [ClickAttack, Lobby, ShulkerDefence, DeathRun, JumpDuell, Survival, BuildPlugin, GameChestPoll, Verify]

commands:
  opme:
  serverid:
    aliases: [sid]
  nick:
  fakeplugins: