name: GameChest
version: mvn:unknown
#description
author: ByteList
main: de.gamechest.GameChest

loadbefore: [ViaVersion, ClickAttack, Lobby, ShulkerDefence, DeathRun, JumpDuell, Survival, BuildPlugin, GameChestPoll, Verify, ImageToMap]

commands:
  opme:
  serverid:
    aliases: [sid]
  nick:
  fakeplugins:
  website: